### ISSUE TITLE
Undefined columns selected when running rsam()

### ISSUE THREAD

**Issue by thercast** [yonicd/rsam#1]
My thanks for creating such a useful package for RStudio addins!  I installed the package from the GitHub repo and when I execute `rsam::rsam()` I receive an error that undefined columns were selected.  I did a bit of debugging and noticed that my version of the `this` data frame created in the early portion of `rsam.R` does not contain the __Shortcut__ column.  You can see the first few rows of my version of `this` in the table below.  I'm running R 3.4.2 with RStudio Desktop 1.1.383 on Ubuntu 17.10 (detailed session information below).  Let me know if you'd like more information.

|Key                         |Hide  |Show |Package  |Name                |Description                                                                    |Binding           |Interactive |libpath                                                                   |
|:---------------------------|:-----|:----|:--------|:-------------------|:------------------------------------------------------------------------------|:-----------------|:-----------|:-------------------------------------------------------------------------|
|blogdown::new_post_addin    |false |TRUE |blogdown |New Post            |Create a new post with blogdown::new_post().                                   |new_post_addin    |true        |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/blogdown/rstudio/_addins.dcf |
|blogdown::serve_site        |false |TRUE |blogdown |Serve Site          |Run blogdown::serve_site() to live preview a website locally.                  |serve_site        |true        |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/blogdown/rstudio/_addins.dcf |
|blogdown::update_meta_addin |false |TRUE |blogdown |Update Metadata     |Update the title, author, date, categories, and tags of the current blog post. |update_meta_addin |true        |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/blogdown/rstudio/_addins.dcf |
|bookdown::mathquill         |false |TRUE |bookdown |Input LaTeX Math    |Input math expressions via the MathQuill library.                              |mathquill         |true        |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/bookdown/rstudio/_addins.dcf |
|bookdown::serve_book        |false |TRUE |bookdown |Preview Book        |Run bookdown::serve_book() to live preview a book.                             |serve_book        |true        |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/bookdown/rstudio/_addins.dcf |
|clipr::clipr_output         |false |TRUE |clipr    |Output to clipboard |Copies the console output of a selected expression to the system clipboard     |clipr_output      |false       |/home/eric/R/x86_64-pc-linux-gnu-library/3.4/clipr/rstudio/_addins.dcf    |

```r
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/Fort_Wayne          
 date     2018-01-09                  

Packages -----------------------------------------------------------------------------------------------------
 package       * version  date       source        
 backports       1.1.2    2017-12-13 CRAN (R 3.4.2)
 base          * 3.4.2    2017-10-12 local         
 commonmark      1.4      2017-09-01 CRAN (R 3.4.2)
 compiler        3.4.2    2017-10-12 local         
 data.table      1.10.4-3 2017-10-27 CRAN (R 3.4.2)
 datasets      * 3.4.2    2017-10-12 local         
 devtools        1.13.4   2017-11-09 CRAN (R 3.4.2)
 digest          0.6.13   2017-12-14 CRAN (R 3.4.2)
 evaluate        0.10.1   2017-06-24 CRAN (R 3.4.2)
 graphics      * 3.4.2    2017-10-12 local         
 grDevices     * 3.4.2    2017-10-12 local         
 highr           0.6      2016-05-09 CRAN (R 3.4.2)
 htmltools       0.3.6    2017-04-28 CRAN (R 3.4.2)
 htmlwidgets     0.9      2017-07-10 CRAN (R 3.4.2)
 httpuv          1.3.5    2017-07-04 CRAN (R 3.4.2)
 jsonlite        1.5      2017-06-01 CRAN (R 3.4.2)
 knitr           1.18     2017-12-27 CRAN (R 3.4.2)
 magrittr        1.5      2014-11-22 CRAN (R 3.4.2)
 memoise         1.1.0    2017-04-21 CRAN (R 3.4.2)
 methods       * 3.4.2    2017-10-12 local         
 mime            0.5      2016-07-07 CRAN (R 3.4.2)
 miniUI          0.1.1    2016-01-15 CRAN (R 3.4.2)
 R6              2.2.2    2017-06-17 CRAN (R 3.4.2)
 Rcpp            0.12.14  2017-11-23 CRAN (R 3.4.2)
 rhandsontable   0.3.4    2016-11-03 CRAN (R 3.4.2)
 roxygen2        6.0.1    2017-02-06 CRAN (R 3.4.2)
 rprojroot       1.3-2    2018-01-03 CRAN (R 3.4.2)
 rsam          * 0.1.0    <NA>       local         
 shiny         * 1.0.5    2017-08-23 CRAN (R 3.4.2)
 stats         * 3.4.2    2017-10-12 local         
 stringi         1.1.6    2017-11-17 CRAN (R 3.4.2)
 stringr         1.2.0    2017-02-18 CRAN (R 3.4.2)
 tools           3.4.2    2017-10-12 local         
 usethis       * 1.1.0    2017-11-17 CRAN (R 3.4.2)
 utils         * 3.4.2    2017-10-12 local         
 withr           2.1.1    2017-12-19 CRAN (R 3.4.2)
 xml2            1.1.1    2017-01-24 CRAN (R 3.4.2)
 xtable          1.8-2    2016-02-05 CRAN (R 3.4.2)
 yaml            2.1.16   2017-12-12 CRAN (R 3.4.2)
```

**Comment by yonicd** [comment]
thanks for trying out the package. 

what does `rsam::fetch_addins()` return?

**Comment by yonicd** [comment]
thanks for trying out the package. 

this https://github.com/yonicd/rsam/commit/9ebbe7a58d5e08a0308030d0265d268144d2c848 should fix the problem

**Comment by thercast** [comment]
Yes that solved the issue.  Thanks for the quick fix!
