### ISSUE TITLE
Reprex stops working after rsam install?

### ISSUE THREAD

**Issue by batpigandme** [yonicd/rsam#2]
So, I'm not 100% on what's going on here, but after I installed rsam, I started getting reprex errors re. Addins not working properly. I played around with things, tested reprex on rstudio server pro, still working. And, ultimately, uninstalled rsam, _but_ I keep on getting rsam-related errors in reprexes now, e.g.
![image](https://user-images.githubusercontent.com/831732/35200087-e3987a0a-fed5-11e7-95aa-8fc338cb52f9.png)
Any thoughts on this? Sorry I'm not describing it very well, I'm just baffled at this point… ¯\\(°_o)/¯

**Comment by batpigandme** [comment]
Also, after reinstall, rsam isn't working now either it looks like…
![Imgur](https://i.imgur.com/DDvXaWv.gif)

**Comment by batpigandme** [comment]
Sweet! It was totally fine, and then I installed the dev version and things got wonky. But, the patch worked so 🎉!

**Comment by yonicd** [comment]
good to hear.
